#!/usr/bin/env python3
"""Regenerate .github/workflows/rebuild.yml (dropdown lists come from config/boards)."""
import subprocess

def boards_list():
    out = subprocess.run(["bash", "-c", "ls config/boards | sed 's/\\.[^.]*$//' | sort -u"],
                         capture_output=True, text=True, check=True).stdout
    return [l.strip() for l in out.splitlines() if l.strip()]

def families_list():
    out = subprocess.run(["bash", "-c", "grep -h '^BOARDFAMILY=' config/boards/*.conf config/boards/*.csc config/boards/*.eos 2>/dev/null"],
                         capture_output=True, text=True, check=True).stdout
    fams = set()
    for l in out.splitlines():
        m = l.split('"')
        if len(m) >= 2:
            fams.add(m[1].strip())
    return sorted(f for f in fams if f)

boards = boards_list()
boards_main = [b for b in boards if b != "kc2-k10plus"]
board_options = ["kc2-k10plus"] + boards_main + ["custom"]
fams = families_list()
fams = ["rockchip64"] + [f for f in fams if f != "rockchip64"]

y = []
A = y.append
A('name: rebuild')
A('')
A('# KC2/K10Plus custom image builder for the vseal001/armbian-build fork.')
A('#')
A('# - Manual "web trigger": run from the Actions tab (workflow_dispatch).')
A('# - Nightly build + upstream sync: OFF by default. Turn it on with the')
A('#   repository variable NIGHTLY_ENABLED=true (Settings -> Secrets and')
A('#   variables -> Actions -> Variables tab). Cron below is UTC 20:37 = 04:37 Beijing.')
A('#')
A('# Defaults build our kc2-k10plus board with the xfce desktop.')
A('')
A('on:')
A('  workflow_dispatch:')
A('    inputs:')
A('      arch:')
A('        description: "平台架构 / target architecture (informational for most boards)"')
A('        required: true')
A('        default: "arm64"')
A('        type: choice')
A('        options: [arm64, armhf, amd64, riscv64]')
A('      soc:')
A('        description: "CPU 主控 / SoC family (sanity check against selected board)"')
A('        required: true')
A('        default: "rockchip64"')
A('        type: choice')
A('        options:')
for f in fams:
    A(f'          - "{f}"')
A('      board:')
A('        description: "型号 / board (all boards in this fork + custom)"')
A('        required: true')
A('        default: "kc2-k10plus"')
A('        type: choice')
A('        options:')
for b in board_options:
    A(f'          - "{b}"')
A('      board_override:')
A('        description: "型号选 custom 时, 在这里填实际板卡名"')
A('        required: false')
A('        default: ""')
A('        type: string')
A('      desktop:')
A('        description: "桌面版本 / desktop environment"')
A('        required: true')
A('        default: "xfce"')
A('        type: choice')
A('        options: [xfce, gnome, lxde, kde-plasma, none]')
A('      branch:')
A('        description: "内核分支 / kernel branch"')
A('        required: true')
A('        default: "current"')
A('        type: choice')
A('        options: [current, edge]')
A('      release:')
A('        description: "发行版 / userland release"')
A('        required: true')
A('        default: "trixie"')
A('        type: choice')
A('        options: [trixie, bookworm]')
A('      sync_upstream:')
A('        description: "先合并上游 armbian/build main 再构建 / sync upstream first"')
A('        required: true')
A('        default: false')
A('        type: boolean')
A('  schedule:')
A('    - cron: "37 20 * * *"   # nightly, gated by NIGHTLY_ENABLED repo variable (default off)')
A('')
A('permissions:')
A('  contents: write')
A('')
A('concurrency:')
A('  group: rebuild-${{ github.ref }}')
A('  cancel-in-progress: false')
A('')
A('jobs:')
A('  build:')
A('    name: Rebuild Armbian image')
A('    runs-on: ubuntu-22.04')
A('    timeout-minutes: 360')
A("    # nightly runs only pass this gate when the repo variable NIGHTLY_ENABLED=true")
A("    if: github.event_name != 'schedule' || vars.NIGHTLY_ENABLED == 'true'")
A('    env:')
A('      IN_ARCH: ${{ inputs.arch }}')
A('      IN_SOC: ${{ inputs.soc }}')
A('      IN_BOARD: ${{ inputs.board }}')
A('      IN_BOARD_OVERRIDE: ${{ inputs.board_override }}')
A('      IN_DESKTOP: ${{ inputs.desktop }}')
A('      IN_BRANCH: ${{ inputs.branch }}')
A('      IN_RELEASE: ${{ inputs.release }}')
A('      IN_SYNC_UPSTREAM: ${{ inputs.sync_upstream }}')
A('    steps:')
A('      - uses: actions/checkout@v4')
A('        with:')
A('          fetch-depth: 0')
A('')
A('      - name: Resolve build parameters')
A('        run: |')
A('          # scheduled runs carry no inputs -> defaults: kc2-k10plus + xfce desktop')
A('          BOARD="${IN_BOARD:-kc2-k10plus}"')
A('          if [ "$BOARD" = "custom" ]; then')
A('            BOARD="${IN_BOARD_OVERRIDE}"')
A('            [ -n "$BOARD" ] || { echo "::error::board=custom needs board_override"; exit 1; }')
A('          fi')
A('          BRANCH="${IN_BRANCH:-current}"')
A('          RELEASE="${IN_RELEASE:-trixie}"')
A('          DESKTOP="${IN_DESKTOP:-xfce}"')
A('          ARCH="${IN_ARCH:-arm64}"')
A('          SOC="${IN_SOC:-rockchip64}"')
A('          if [ "$DESKTOP" = "none" ]; then')
A('            BUILD_DESKTOP="no"; DE=""')
A('          else')
A('            BUILD_DESKTOP="yes"; DE="$DESKTOP"')
A('          fi')
A('          # soft sanity checks (do not block the build)')
A('          fam=$(grep -h "^BOARDFAMILY=" "config/boards/${BOARD}".* 2>/dev/null | head -1 | sed \'s/^BOARDFAMILY="\\([^"]*\\)".*/\\1/\')')
A('          [ -n "$fam" ] || { echo "::error::board $BOARD not found in config/boards"; exit 1; }')
A('          [ "$fam" = "$SOC" ] || echo "::warning::selected SoC family \'$SOC\' != board family \'$fam\' (continuing)"')
A('          [ "$ARCH" = "arm64" ] || echo "::warning::arch \'$ARCH\' selected - most rockchip64 boards are arm64 only"')
A('          {')
A('            echo "BOARD=$BOARD"')
A('            echo "BRANCH=$BRANCH"')
A('            echo "RELEASE=$RELEASE"')
A('            echo "DESKTOP=$DESKTOP"')
A('            echo "ARCH=$ARCH"')
A('            echo "SOC=$SOC"')
A('            echo "BUILD_DESKTOP=$BUILD_DESKTOP"')
A('            echo "DE=$DE"')
A('          } >> "$GITHUB_ENV"')
A('')
A("      - name: Sync upstream armbian/build (nightly or on request)")
A("        if: github.event_name == 'schedule' || env.IN_SYNC_UPSTREAM == 'true'")
A('        run: |')
A('          git config user.name "github-actions[bot]"')
A('          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"')
A('          git remote add upstream https://github.com/armbian/build.git')
A('          git fetch upstream main')
A('          git merge --no-edit upstream/main')
A('          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then')
A('            git push origin main')
A('          else')
A('            echo "::notice::merged upstream into $(git branch --show-current); push skipped (not on main)"')
A('          fi')
A('')
A('      - name: Free disk space')
A('        run: |')
A('          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL || true')
A('          df -h /')
A('')
A('      - name: Build image')
A('        run: |')
A('          sudo -E ./compile.sh build \\')
A('            BOARD="$BOARD" \\')
A('            BRANCH="$BRANCH" \\')
A('            RELEASE="$RELEASE" \\')
A('            BUILD_DESKTOP="$BUILD_DESKTOP" \\')
A('            DESKTOP_ENVIRONMENT="$DE" \\')
A('            DESKTOP_TIER=mid \\')
A('            BUILD_MINIMAL=no \\')
A('            KERNEL_CONFIGURE=no \\')
A('            COMPRESS_OUTPUTIMAGE=sha,img')
A('')
A('      - name: Upload images')
A('        if: always()')
A('        uses: actions/upload-artifact@v4')
A('        with:')
A('          name: armbian-${{ env.BOARD }}-${{ env.BRANCH }}-${{ env.RELEASE }}-${{ env.DESKTOP }}')
A('          path: output/images/')
A('          if-no-files-found: error')
A('')
A('      - name: Upload build logs')
A('        if: always()')
A('        uses: actions/upload-artifact@v4')
A('        with:')
A('          name: build-logs-${{ github.run_number }}')
A('          path: output/logs/')
A('          if-no-files-found: ignore')

open(".github/workflows/rebuild.yml", "w", encoding="utf-8").write("\n".join(y) + "\n")
print(f"wrote rebuild.yml: {len(y)} lines, {len(board_options)} board options, {len(fams)} families")
