#!/usr/bin/env python3
"""Regenerate .github/workflows/rebuild.yml.

The board dropdown is grouped by BOARDFAMILY (kc2-k10plus stays first as the
default), alphabetical within each family. Re-run after upstream syncs so the
menu tracks config/boards (the sync-upstream workflow calls this automatically).
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BOARDS_DIR = ROOT / "config" / "boards"
OUT = ROOT / ".github" / "workflows" / "rebuild.yml"

DESKTOPS = ["xfce", "gnome", "kde-plasma", "cinnamon", "mate", "lxqt", "i3-wm", "none"]


def family_of(path: Path) -> str:
    try:
        m = re.search(r'BOARDFAMILY="([^"]+)"', path.read_text(encoding="utf-8", errors="replace"))
        return m.group(1).strip() if m else "zzz-unknown"
    except OSError:
        return "zzz-unknown"


def collect():
    boards = []
    fams = set()
    for p in sorted(BOARDS_DIR.iterdir()):
        if not p.is_file() or p.suffix not in (".conf", ".csc", ".eos", ".tvb", ".wip"):
            continue
        name = p.name.rsplit(".", 1)[0]
        fam = family_of(p)
        fams.add(fam)
        if name != "kc2-k10plus":
            boards.append((name, fam))
    boards.sort(key=lambda t: (t[1], t[0]))  # family groups, ABC inside each
    board_options = ["kc2-k10plus"] + [b for b, _ in boards]
    fams_sorted = ["rockchip64"] + sorted(f for f in fams if f != "rockchip64")
    return board_options, fams_sorted


board_options, fams = collect()

y = []
A = y.append
A("name: rebuild")
A("")
A("# KC2/K10Plus custom image builder for the vseal001/armbian-build fork.")
A("#")
A('# - Manual "web trigger": run from the Actions tab (workflow_dispatch).')
A("# - Nightly build + upstream sync: OFF by default. Turn it on with the")
A("#   repository variable NIGHTLY_ENABLED=true (Settings -> Secrets and")
A("#   variables -> Actions -> Variables tab). Cron below is UTC 20:37 = 04:37 Beijing.")
A("#")
A("# Defaults build our kc2-k10plus board with the xfce desktop.")
A("# NOTE: GitHub dispatch menus cannot cascade; the board list is grouped by")
A("# CPU family instead - pick CPU family first, boards of that family sit")
A("# together alphabetically. Regenerate via custom-model/tools/gen_rebuild_yml.py")
A("# (sync-upstream workflow does this automatically after merges).")
A("")
A("on:")
A("  workflow_dispatch:")
A("    inputs:")
A("      arch:")
A('        description: "1. 平台架构 / target architecture (informational for most boards)"')
A("        required: true")
A('        default: "arm64"')
A("        type: choice")
A("        options: [arm64, armhf, amd64, riscv64]")
A("      soc:")
A('        description: "2. CPU 主控 / SoC family - 先选这里, 型号列表按家族分组; 选错会在校验步列出该家族全部板卡"')
A("        required: true")
A('        default: "rockchip64"')
A("        type: choice")
A("        options:")
for f in fams:
    A(f'          - "{f}"')
A("      board:")
A('        description: "3. 型号 / board - 同家族板卡排在一起按 ABC 排列; 没有就选 custom 并填下一项"')
A("        required: true")
A('        default: "kc2-k10plus"')
A("        type: choice")
A("        options:")
for b in board_options:
    A(f'          - "{b}"')
A('      board_override:')
A('        description: "型号选 custom 时, 在这里填实际板卡名"')
A("        required: false")
A('        default: ""')
A("        type: string")
A("      desktop:")
A('        description: "4. 桌面版本 / desktop environment (全部 arm64 上游支持桌面; openssh 等必备组件默认已含)"')
A("        required: true")
A('        default: "xfce"')
A("        type: choice")
A("        options: [" + ", ".join(DESKTOPS) + "]")
A("      extra_packages:")
A('        description: "5. 额外组件 / extra packages, 空格分隔, 如: git python3-dev htop"')
A("        required: false")
A('        default: ""')
A("        type: string")
A("      branch:")
A('        description: "内核分支 / kernel branch"')
A("        required: true")
A('        default: "current"')
A("        type: choice")
A("        options: [current, edge]")
A("      release:")
A('        description: "发行版 / userland release"')
A("        required: true")
A('        default: "trixie"')
A("        type: choice")
A("        options: [trixie, bookworm]")
A("      sync_upstream:")
A('        description: "构建前先合并上游 armbian/build main / sync upstream first"')
A("        required: true")
A("        default: false")
A("        type: boolean")
A("  schedule:")
A('    - cron: "37 20 * * *"   # nightly, gated by NIGHTLY_ENABLED repo variable (default off)')
A("")
A("permissions:")
A("  contents: write")
A("  issues: write")
A("")
A("concurrency:")
A("  group: rebuild-${{ github.ref }}")
A("  cancel-in-progress: false")
A("")
A("jobs:")
A("  build:")
A("    name: Rebuild Armbian image")
A("    runs-on: ubuntu-22.04")
A("    timeout-minutes: 360")
A("    # nightly runs only pass this gate when the repo variable NIGHTLY_ENABLED=true")
A("    if: github.event_name != 'schedule' || vars.NIGHTLY_ENABLED == 'true'")
A("    env:")
A("      IN_ARCH: ${{ inputs.arch }}")
A("      IN_SOC: ${{ inputs.soc }}")
A("      IN_BOARD: ${{ inputs.board }}")
A("      IN_BOARD_OVERRIDE: ${{ inputs.board_override }}")
A("      IN_DESKTOP: ${{ inputs.desktop }}")
A("      IN_EXTRA: ${{ inputs.extra_packages }}")
A("      IN_BRANCH: ${{ inputs.branch }}")
A("      IN_RELEASE: ${{ inputs.release }}")
A("      IN_SYNC_UPSTREAM: ${{ inputs.sync_upstream }}")
A("    steps:")
A("      - uses: actions/checkout@v4")
A("        with:")
A("          fetch-depth: 0")
A("")
A("      - name: Resolve build parameters")
A("        run: |")
A("          # scheduled runs carry no inputs -> defaults: kc2-k10plus + xfce desktop")
A('          BOARD="${IN_BOARD:-kc2-k10plus}"')
A('          if [ "$BOARD" = "custom" ]; then')
A('            BOARD="${IN_BOARD_OVERRIDE}"')
A('            [ -n "$BOARD" ] || { echo "::error::board=custom needs board_override"; exit 1; }')
A("          fi")
A('          BRANCH="${IN_BRANCH:-current}"')
A('          RELEASE="${IN_RELEASE:-trixie}"')
A('          DESKTOP="${IN_DESKTOP:-xfce}"')
A('          ARCH="${IN_ARCH:-arm64}"')
A('          SOC="${IN_SOC:-rockchip64}"')
A('          EXTRA="${IN_EXTRA}"')
A('          if [ "$DESKTOP" = "none" ]; then')
A('            BUILD_DESKTOP="no"; DE=""')
A("          else")
A('            BUILD_DESKTOP="yes"; DE="$DESKTOP"')
A("          fi")
A("          # hard family check: wrong CPU family -> list that family's boards and stop")
A('          fam=$(grep -h "^BOARDFAMILY=" "config/boards/${BOARD}".* 2>/dev/null | head -1 | sed \'s/^BOARDFAMILY="\\([^"]*\\)".*/\\1/\')')
A('          [ -n "$fam" ] || { echo "::error::board $BOARD not found in config/boards"; exit 1; }')
A('          if [ "$fam" != "$SOC" ]; then')
A('            same=$(grep -l "^BOARDFAMILY=\\"$SOC\\"" config/boards/* 2>/dev/null | sed \'s|.*/||; s|\\.[^.]*$||\' | sort | head -40 | tr "\\n" " ")')
A('            echo "::error::board \'$BOARD\' is CPU family \'$fam\', not \'$SOC\'. Boards of family \'$SOC\': $same"')
A("            exit 1")
A("          fi")
A('          [ "$ARCH" = "arm64" ] || echo "::warning::arch \'$ARCH\' selected - most rockchip64 boards are arm64 only"')
A("          {")
A('            echo "BOARD=$BOARD"')
A('            echo "BRANCH=$BRANCH"')
A('            echo "RELEASE=$RELEASE"')
A('            echo "DESKTOP=$DESKTOP"')
A('            echo "ARCH=$ARCH"')
A('            echo "SOC=$SOC"')
A('            echo "EXTRA=$EXTRA"')
A('            echo "BUILD_DESKTOP=$BUILD_DESKTOP"')
A('            echo "DE=$DE"')
A('          } >> "$GITHUB_ENV"')
A("")
A("      - name: Sync upstream armbian/build (nightly or on request)")
A("        if: github.event_name == 'schedule' || env.IN_SYNC_UPSTREAM == 'true'")
A("        run: |")
A('          git config user.name "github-actions[bot]"')
A('          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"')
A("          git remote add upstream https://github.com/armbian/build.git")
A("          git fetch upstream main")
A("          git merge --no-edit upstream/main")
A('          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then')
A("            git push origin main")
A("          else")
A('            echo "::notice::merged upstream into $(git branch --show-current); push skipped (not on main)"')
A("          fi")
A("")
A("      - name: Free disk space")
A("        run: |")
A("          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL || true")
A("          df -h /")
A("")
A("      - name: Build image")
A("        run: |")
A("          sudo -E ./compile.sh build \\")
A('            BOARD="$BOARD" \\')
A('            BRANCH="$BRANCH" \\')
A('            RELEASE="$RELEASE" \\')
A('            BUILD_DESKTOP="$BUILD_DESKTOP" \\')
A('            DESKTOP_ENVIRONMENT="$DE" \\')
A("            DESKTOP_TIER=mid \\")
A("            BUILD_MINIMAL=no \\")
A("            KERNEL_CONFIGURE=no \\")
A("            COMPRESS_OUTPUTIMAGE=sha,img \\")
A('            PACKAGE_LIST_ADDITIONAL="$EXTRA"')
A("")
A("      - name: Publish image as release (persistent download link)")
A("        if: success()")
A("        env:")
A("          GH_TOKEN: ${{ github.token }}")
A("        run: |")
A('          if compgen -G "output/images/*.img" > /dev/null || compgen -G "output/images/*.img.xz" > /dev/null; then')
A('            TAG="img-${BOARD}-$(date -u +%Y%m%d-%H%M%S)"')
A('            gh release create "$TAG" output/images/* \\')
A('              --title "Armbian ${BOARD} ${BRANCH}/${RELEASE} ${DESKTOP}" \\')
A('              --notes "自动构建产物。日志: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"')
A('            echo "RELEASE_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/${TAG}" >> "$GITHUB_ENV"')
A("          else")
A('            echo "::warning::no image files found in output/images"; echo "RELEASE_URL=" >> "$GITHUB_ENV"')
A("          fi")
A("")
A("      - name: Notify via tracking issue (GitHub email to repo owner)")
A("        if: success()")
A("        env:")
A("          GH_TOKEN: ${{ github.token }}")
A("        run: |")
A('          TITLE="📦 构建通知 / build notifications"')
A('          NUM=$(gh issue list --search "${TITLE} in:title" --author "app/github-actions[bot]" --state open --json number --jq ".[0].number // empty")')
A('          if [ -z "$NUM" ]; then')
A('            NUM=$(gh issue create --title "$TITLE" \\')
A('              --body "本 issue 由 rebuild workflow 自动维护：每次构建成功会在此评论镜像下载链接。仓库所有者会收到 GitHub 邮件通知（可在 Settings -> Notifications 调整）。" \\')
A('              | grep -oE "[0-9]+$")')
A("          fi")
A('          gh issue comment "$NUM" --body "✅ **${BOARD}** ${BRANCH}/${RELEASE} · ${DESKTOP} 构建完成（额外组件: ${EXTRA:-无}）')
A('          - 镜像下载: ${RELEASE_URL:-（本跑无镜像文件，见 artifact）}')
A('          - 构建日志: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"')
A("")
A("      - name: Upload images artifact")
A("        if: always()")
A("        uses: actions/upload-artifact@v4")
A("        with:")
A("          name: armbian-${{ env.BOARD }}-${{ env.BRANCH }}-${{ env.RELEASE }}-${{ env.DESKTOP }}")
A("          path: output/images/")
A("          if-no-files-found: error")
A("")
A("      - name: Upload build logs")
A("        if: always()")
A("        uses: actions/upload-artifact@v4")
A("        with:")
A("          name: build-logs-${{ github.run_number }}")
A("          path: output/logs/")
A("          if-no-files-found: ignore")

OUT.write_text("\n".join(y) + "\n", encoding="utf-8")
print(f"wrote {OUT.name}: {len(y)} lines, {len(board_options)} board options, {len(fams)} families, desktops={len(DESKTOPS)}")
