# Rockchip RK3399 hexa core HDMI TV box (KC2 / K10Plus), AP6354 WiFi, GbE
BOARD_NAME="KC2 / K10Plus"
BOARD_VENDOR="kc2"
BOARDFAMILY="rockchip64"
BOARD_MAINTAINER=""
INTRODUCED="2026"
BOOTCONFIG="firefly-rk3399_defconfig"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3399-kc2-k10plus.dtb"
SRC_EXTLINUX="yes"
SRC_CMDLINE="console=ttyS2,1500000 console=tty0"
# IR receiver keymap loader (Haigesen 3528 remote)
PACKAGE_LIST_BOARD="ir-keytable"
